# Generated by Django 2.2.5 on 2019-11-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app25', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='contact',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
